In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeRegressor
from sklearn import svm,datasets
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [3]:
df = pd.read_csv("hepatotoxicity_ALT_KlekFP_ready_set_after_conversion.csv", header=0, index_col=False)

In [4]:
df.head()

ALT  KRFP1  KRFP2  KRFP3  KRFP4  KRFP5  KRFP6  KRFP7  KRFP8  KRFP9  ...  \
0  32.60    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
1  37.20    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
2   2.92    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
3   3.16    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4  44.10    1.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

   KRFP4851  KRFP4852  KRFP4853  KRFP4854  KRFP4855  KRFP4856  KRFP4857  \
0       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
1       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
2       0.0       1.0       0.0       0.0       0.0       1.0       0.0   
3       0.0       1.0       0.0       0.0       0.0       1.0       0.0   
4       0.0       0.0       0.0       0.0       0.0       0.0       0.0   

   KRFP4858  KRFP4859  KRFP4860  
0       0.0       0.0       0.0  
1       0.0       0.0       0.0  
2       0.0       0.0       0.0  
3       0.0       0.0       0.0  
4       0.0       0.0       0.0  

[5 rows x 4861 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Columns: 4861 entries, ALT to KRFP4860
dtypes: float64(4861)
memory usage: 3.6 MB


In [6]:
df.describe()

ALT      KRFP1      KRFP2  KRFP3  KRFP4  KRFP5  KRFP6  KRFP7  \
count   98.000000  98.000000  98.000000   98.0   98.0   98.0   98.0   98.0   
mean    47.119898   0.693878   0.418367    0.0    0.0    0.0    0.0    0.0   
std     45.294039   0.463251   0.495827    0.0    0.0    0.0    0.0    0.0   
min      1.510000   0.000000   0.000000    0.0    0.0    0.0    0.0    0.0   
25%     29.775000   0.000000   0.000000    0.0    0.0    0.0    0.0    0.0   
50%     36.300000   1.000000   0.000000    0.0    0.0    0.0    0.0    0.0   
75%     49.000000   1.000000   1.000000    0.0    0.0    0.0    0.0    0.0   
max    273.000000   1.000000   1.000000    0.0    0.0    0.0    0.0    0.0   

       KRFP8  KRFP9  ...  KRFP4851   KRFP4852  KRFP4853  KRFP4854  KRFP4855  \
count   98.0   98.0  ...      98.0  98.000000      98.0      98.0      98.0   
mean     0.0    0.0  ...       0.0   0.051020       0.0       0.0       0.0   
std      0.0    0.0  ...       0.0   0.221171       0.0       0.0       0.0   
min      0.0    0.0  ...       0.0   0.000000       0.0       0.0       0.0   
25%      0.0    0.0  ...       0.0   0.000000       0.0       0.0       0.0   
50%      0.0    0.0  ...       0.0   0.000000       0.0       0.0       0.0   
75%      0.0    0.0  ...       0.0   0.000000       0.0       0.0       0.0   
max      0.0    0.0  ...       0.0   1.000000       0.0       0.0       0.0   

        KRFP4856  KRFP4857  KRFP4858  KRFP4859  KRFP4860  
count  98.000000      98.0      98.0      98.0      98.0  
mean    0.051020       0.0       0.0       0.0       0.0  
std     0.221171       0.0       0.0       0.0       0.0  
min     0.000000       0.0       0.0       0.0       0.0  
25%     0.000000       0.0       0.0       0.0       0.0  
50%     0.000000       0.0       0.0       0.0       0.0  
75%     0.000000       0.0       0.0       0.0       0.0  
max     1.000000       0.0       0.0       0.0       0.0  

[8 rows x 4861 columns]

In [7]:
columns = list(dataframe.columns.values)
columns.remove('ALT')

X = dataframe[columns].values
y = dataframe['ALT'].values

In [13]:
print(y)

[ 32.6   37.2    2.92   3.16  44.1   43.21  36.    22.8   27.1   35.9
  45.3   28.1   40.    80.   273.    28.    38.6  247.5  261.    57.
  26.4   25.    31.    49.    32.    28.    45.    34.    34.    43.
  41.    68.    40.6   61.14  30.     2.27   1.51   1.89  66.6   32.8
  60.    32.    61.    44.   220.    22.7   26.    49.    31.4   40.
  20.    25.    64.    49.    74.9   33.    34.4   36.7   33.4   55.7
  37.8   44.2   21.6   36.6   35.1   31.    36.    50.    29.    57.
  35.    49.    64.    41.9   43.2   39.3   25.    30.9   30.    20.
  45.3   29.7   35.5   23.3   64.    29.    17.    49.    20.    64.
  64.    79.4   33.7   38.3   32.    53.55  34.5   60.  ]


In [14]:
print(X)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
